#!/bin/zsh

# Desk Presence — install as a launchd user agent.
#
# Why this copies files instead of running them in place: macOS TCC refuses
# launchd-spawned processes read access to /Volumes/workspace (an SMB mount), so an
# agent pointed at the repo dies on every spawn with
#
#     can't open file '/Volumes/workspace/Synergy/desk_presence.py':
#     [Errno 1] Operation not permitted
#
# Installing into the home directory also removes the boot-ordering dependency on
# com.local.mount-workspace, which mounts that volume.
#
# Re-run this after changing desk_presence.py, config.py, or mqtt_clients/.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LABEL="com.synergy.deskpresence"

# Resolve the REAL home, never $HOME. Under a profile-scoped tool (Claude Code with
# ~/.claude-profiles/<p>) $HOME points at the profile dir, and a LaunchAgent written
# there is never scanned at login -- it installs "successfully" and then does not
# survive a reboot, which is the whole point of this script.
REALHOME="$(dscl . -read "/Users/$(id -un)" NFSHomeDirectory 2>/dev/null | awk '{print $2}')"
[ -d "$REALHOME" ] || REALHOME="/Users/$(id -un)"
[ -d "$REALHOME" ] || { echo "ERROR: cannot resolve a real home directory"; exit 1; }
case "$REALHOME" in
  *.claude-profiles*) echo "ERROR: resolved a profile dir ($REALHOME), refusing"; exit 1 ;;
esac

INSTALL_DIR="$REALHOME/.local/share/desk-presence"
LOG_DIR="$REALHOME/Library/Logs/desk-presence"
LAUNCHD_DIR="$REALHOME/Library/LaunchAgents"
PLIST_DEST="$LAUNCHD_DIR/$LABEL.plist"

BROKER="${MQTT_BROKER:-192.168.4.3}"
PORT="${MQTT_PORT:-1883}"
TOPIC="${DESK_TOPIC:-desk/presence}"
INTERVAL="${DESK_INTERVAL:-30}"
IDLE_THRESHOLD="${DESK_IDLE_THRESHOLD:-900}"
HOST_NAME="${DESK_HOST_NAME:-studio}"   # the Synergy screen name, not $(hostname -s) = studio-3
PYTHON="${DESK_PYTHON:-/usr/bin/python3}"

echo "=== Desk Presence Installation ==="
echo ""

if [ "$(id -u)" = "0" ]; then
    echo "ERROR: Do not run this script as root/sudo."
    echo "This is a LaunchAgent and must run as your user account."
    exit 1
fi

if ! "$PYTHON" -c "import paho.mqtt.client" 2>/dev/null; then
    echo "ERROR: $PYTHON cannot import paho.mqtt.client"
    echo "Install it, or set DESK_PYTHON to an interpreter that has it."
    exit 1
fi
echo "✓ $PYTHON has paho-mqtt"

echo "Installing runtime to $INSTALL_DIR ..."
mkdir -p "$INSTALL_DIR" "$LOG_DIR" "$LAUNCHD_DIR"
cp "$SCRIPT_DIR/desk_presence.py" "$INSTALL_DIR/"
cp "$SCRIPT_DIR/config.py" "$INSTALL_DIR/"
rm -rf "$INSTALL_DIR/mqtt_clients"
cp -R "$SCRIPT_DIR/mqtt_clients" "$INSTALL_DIR/"
# .env is deliberately NOT copied: every setting is passed explicitly below, and the
# repo .env carries unrelated config we do not want a second copy of.
find "$INSTALL_DIR" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true

echo "Verifying the installed copy runs ..."
if ! (cd "$INSTALL_DIR" && LOG_DIR="$LOG_DIR" "$PYTHON" desk_presence.py --once --host-name "$HOST_NAME" >/dev/null); then
    echo "ERROR: the installed copy failed its --once probe. Not loading the agent."
    exit 1
fi
echo "✓ installed copy probes HIDIdleTime successfully"

echo "Writing $PLIST_DEST ..."
cat > "$PLIST_DEST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <!-- Generated by install-desk-presence.sh. Edit that script, not this file. -->
    <key>ProgramArguments</key>
    <array>
        <string>$PYTHON</string>
        <string>$INSTALL_DIR/desk_presence.py</string>
        <string>--broker</string><string>$BROKER</string>
        <string>--port</string><string>$PORT</string>
        <string>--topic</string><string>$TOPIC</string>
        <string>--interval</string><string>$INTERVAL</string>
        <string>--idle-threshold</string><string>$IDLE_THRESHOLD</string>
        <string>--host-name</string><string>$HOST_NAME</string>
    </array>

    <key>WorkingDirectory</key>
    <string>$INSTALL_DIR</string>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
        <key>NetworkState</key>
        <true/>
    </dict>

    <key>StandardOutPath</key>
    <string>$LOG_DIR/stdout.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/stderr.log</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>LOG_DIR</key>
        <string>$LOG_DIR</string>
    </dict>

    <key>ThrottleInterval</key>
    <integer>10</integer>

    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
PLIST

plutil -lint "$PLIST_DEST" >/dev/null || { echo "ERROR: generated plist is malformed"; exit 1; }
echo "✓ plist valid"

# Stop any manually-started publisher so we do not run two.
pkill -f 'desk_presence.py --broker' 2>/dev/null && echo "stopped a manually-started publisher" || true

echo "Loading the agent ..."
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
sleep 1
# bootstrap can report EIO from a non-GUI session even when it registers; kickstart
# afterwards is what actually confirms the job runs.
launchctl bootstrap "gui/$(id -u)" "$PLIST_DEST" 2>/dev/null || true
launchctl enable "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl kickstart -k "gui/$(id -u)/$LABEL" 2>/dev/null || true

sleep 5
STATUS="$(launchctl list | grep "$LABEL" || true)"
if [ -z "$STATUS" ]; then
    echo ""
    echo "✗ Agent is not registered."
    echo "  Check: cat $LOG_DIR/stderr.log"
    exit 1
fi

EXIT_CODE="$(echo "$STATUS" | awk '{print $2}')"
PID="$(echo "$STATUS" | awk '{print $1}')"
echo ""
echo "launchctl: pid=$PID last-exit=$EXIT_CODE"

if [ "$PID" = "-" ]; then
    echo "✗ Registered but not running (last exit $EXIT_CODE)."
    echo "  Check: tail $LOG_DIR/stderr.log"
    exit 1
fi

echo ""
echo "✓ Desk Presence installed and running (pid $PID)"
echo ""
echo "  Publishing : $HOST_NAME -> $BROKER:$PORT/$TOPIC every ${INTERVAL}s"
echo "  At-desk if : idle < ${IDLE_THRESHOLD}s"
echo "  Runtime    : $INSTALL_DIR   (copied off /Volumes/workspace; re-run this after edits)"
echo "  Logs       : $LOG_DIR/"
echo "  Home       : $REALHOME   (resolved, not \$HOME)"
echo ""
echo "Useful commands:"
echo "  Status:   launchctl list | grep $LABEL"
echo "  Logs:     tail -f $LOG_DIR/desk-presence.log"
echo "  Restart:  launchctl kickstart -k gui/\$(id -u)/$LABEL"
echo "  Remove:   launchctl bootout gui/\$(id -u)/$LABEL && rm $PLIST_DEST"
